SystemOrganization addCategory: #'EarleyParser-Tests'!
SystemOrganization addCategory: 'EarleyParser-Tests-Collections'!
SystemOrganization addCategory: 'EarleyParser-Tests-Grammar'!
SystemOrganization addCategory: 'EarleyParser-Tests-Implementation'!
SystemOrganization addCategory: 'EarleyParser-Tests-Parsing'!
SystemOrganization addCategory: 'EarleyParser-Tests-Public'!
SystemOrganization addCategory: 'EarleyParser-Tests-Stats'!
